<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Newspaper;

/**
 * JournalRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NewspaperRepository extends \Doctrine\ORM\EntityRepository
{

    /**
     * Cette méthode permet de sortir les derniers journaux
     * @return Newspaper[]
     */
    public function getLastNewspapers() : array {

        $queryBuilder = $this->createQueryBuilder('n')
            ->orderBy('n.createdAt', 'DESC');

        return $queryBuilder->getQuery()->getResult();

    }
}
